name: Create Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        default: production
        required: true    
      sha:
        description: "Git SHA to Build"
        required: false
        type: string
        
jobs:
  create_deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: avakar/create-deployment@v1
        with:
          auto_merge: false
          ref: ${{ inputs.sha || github.ref }}
          environment: ${{ inputs.environment }}
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}