name: Create Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run deploy"
        type: environment
        default: production
        required: true
      sha:
        description: "Git SHA (특정 SHA로 배포하려면 입력)"
        required: false
        type: string

jobs:
  create_deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: avakar/create-deployment@v1
        with:
          auto_merge: false
          ref: ${{ inputs.sha || github.ref }}
          environment: ${{ inputs.environment }}
          required_contexts: "" # To bypass checking entirely
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
