name: Deployment
on: 
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true    
      sha:
        description: "Git SHA to Build"
        required: false
        type: string

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'run tests'

  print_env:
    name: Print Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'sha is ${{ inputs.sha || github.sha }}'

  deploy-dev:
    name: Deploy(Dev)
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'dev deployment'

  deploy-production:
    name: Deploy(Production)
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          env: ${{ inputs.environment }}      

      - uses: actions/checkout@v2
      - run: |
          echo '${{ inputs.environment }} deployment'
          echo ${{ secrets.FOO }}

      - name: update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}          