name: Deploy

on: ['deployment']

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start

      - name: 'Deploy ${{ github.event.deployment.environment }}'
        run: |
          echo ${{ secrets.FOO }}

      - name: update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}          

