name: Deploy

on: ['deployment']

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ github.event.deployment.environment }} 
    steps:
      - uses: actions/checkout@v2
      - name: 'Deploy ${{ github.event.deployment.environment }}'
        run: |
          echo 'YOUR CODE HERE'

