name: Inner Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: "Inner Tests"
        run: |
          echo ${{ github.sha }}
          echo ${{ github.event.deployment.environment }}
