name: Test Deployment
on: deployment

jobs:
  deployment:
    runs-on: ubuntu-latest
    # environment: ${{ github.event.deployment.environment }}
    steps:
      - name: start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          env: ${{ github.event.deployment.environment }}

      - name: 'Deploy ${{ github.event.deployment.environment }}'
        run: |
          echo ${{ secrets.FOO }}
          echo ${{ github.sha }}

      - name: update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}          
