name: Test Env

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        default: production
        required: true    
      sha:
        description: "Git SHA to Build"
        required: false
        type: string
        
jobs:
  create_deployment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: 'Deploy ${{ inputs.environment }}'
        run: |
          echo ${{ secrets.FOO }}
          echo ${{ github.sha }}    