name: Test Deployment
on: deployment

jobs:
  inner_test:
    uses: ./.github/workflows/foo.yml

  deployment:
    needs: inner_test
    runs-on: ubuntu-latest
    environment: ${{ github.event.deployment.environment }}
    steps:
      # - name: start deployment
      #   uses: bobheadxi/deployments@v1
      #   id: deployment
      #   with:
      #     step: start
      #     deployment_id: ${{ github.event.deployment.id }}
      #     env: ${{ github.event.deployment.environment }}

      - name: "Deploy ${{ github.event.deployment.environment }}"
        run: |
          echo ${{ secrets.FOO }}
          echo ${{ github.sha }}
          echo '${{ toJSON(github) }}'

      - name: update deployment status
        uses: bobheadxi/deployments@v1
        if: always() && github.event_name == 'deployment'
        with:
          step: finish
          status: ${{ job.status }}
          env: ${{ github.event.deployment.environment }}
          deployment_id: ${{ github.event.deployment.id }}

  post_deploy:
    needs: deployment
    runs-on: ubuntu-latest
    steps:
      - name: "Print"
        run: |
          echo ${{ github.sha }}
          echo ${{ github.action_status }}

  post_test:
    needs: post_deploy
    uses: ./.github/workflows/foo.yml

  qwerty:
    if: always()
    needs: post_test
    uses: ./.github/workflows/post_deploy.yml
