name: Versioning

on:
  push:
    branches:
      - master

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - uses: go-semantic-release/action@v1
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     prerelease: true
      - uses: cycjimmy/semantic-release-action@v3
        with:
          # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: '@semantic-release/git'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
